### ISSUE TITLE
Installing buildroot plugin from eclipse doesn't work anymore

### ISSUE THREAD

**Issue by jworreth** [mbats/eclipse-buildroot-bundle#20]
Hi,

I'm trying to install eclipse plugin for buildroot from http://buildroot.org/downloads/eclipse/luna to eclipse luna and I'm getting an error message like this :

org.eclipse.equinox.p2.core.ProvisionException

Unable to read repository at https://buildroot.org/downloads/eclipse/luna/content.xml.
Unable to read repository at https://buildroot.org/downloads/eclipse/luna/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

As I was able to install this plugin before, I'm looking for a fix about this. Indeed, this plugin is so awesome to automatically configure eclipse so please fix this bug ;-)
- JWorreth

PS : You can see the error details below:
![image](https://cloud.githubusercontent.com/assets/11389004/11695405/40477370-9eaf-11e5-9eef-41acea670153.png)

**Comment by tpetazzoni** [comment]
Thanks for your report @jworreth. This problem is caused by a change of the Web server configuration, which now enforces the use of https:// using the HSTS mechanism. Unfortunately, Eclispe doesn't seem to recognize the SSL certificate as being valid.

We are working with the people managing the Web server to hopefully fix this soon. In the mean time, you can always copy the entire https://buildroot.org/downloads/eclipse/luna/ hierarchy somewhere on your system, and point Eclipse to it as an update site.

**Comment by jworreth** [comment]
Thank you very much for your answer, and your help @tpetazzoni.
I close this issue because I just try to install eclipse plugin from eclipse "Install new software" and it's working.

Nice job !

jworreth

**Comment by tpetazzoni** [comment]
@jworreth Thanks for getting back to us. The web server configuration has been modified so that the downloads folder no longer enforces HSTS, which should fix the problem, as you observed. Thanks!

**Comment by jworreth** [comment]
@tpetazzoni Thanks to you for your reactive work and your quick fix !

Best regards

jworreth
